[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
[dependencies]
borsh = "1.5.7"
solana-program = "2.3.0"
solana-program-test = "2.2.7"
solana-sdk = "2.3.0"
